# Generated by Django 6.0 on 2025-12-15 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaucetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_address', models.CharField(max_length=42, unique=True)),
                ('last_request_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
