# Generated by Django 6.0 on 2025-12-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bscapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('private_key', models.CharField(max_length=66)),
                ('mnemonic', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FaucetRequest',
        ),
    ]
