# Generated by Django 6.0 on 2025-12-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bscapp', '0002_wallet_delete_faucetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='derivation_path',
            field=models.CharField(default="m/44'/60'/0'/0/0", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='public_key',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(max_length=255),
        ),
    ]
